import React, { useState } from 'react';
import { ForecastWorkspaceData, ForecastLineDTO } from './types';
import { ManualOverrideModal } from './ManualOverrideModal';
import { ForecastCompareModal } from './ForecastCompareModal';
import { ForecastAccuracyModal } from './ForecastAccuracyModal';

interface ForecastWorkspaceProps {
  sessionToken: string;
  data: ForecastWorkspaceData | null;
  loading: boolean;
  onRefresh: (scenario: string, method: string, runRateN: number) => void;
  onOverrideSubmit: (accountId: number, periodCode: string, amount: string, reason: string) => Promise<void>;
  onLockVersion: (versionId: string) => Promise<void>;
}

export const ForecastWorkspace: React.FC<ForecastWorkspaceProps> = ({
  sessionToken,
  data,
  loading,
  onRefresh,
  onOverrideSubmit,
  onLockVersion,
}) => {
  const [scenario, setScenario] = useState<string>('base');
  const [defaultMethod, setDefaultMethod] = useState<string>('run_rate');
  const [runRateN, setRunRateN] = useState<number>(3);
  const [locking, setLocking] = useState<boolean>(false);
  const [searchTerm, setSearchTerm] = useState<string>('');

  // Modals state
  const [overrideTarget, setOverrideTarget] = useState<{
    line: ForecastLineDTO;
    periodCode: string;
    amount: string;
  } | null>(null);
  const [showCompare, setShowCompare] = useState<boolean>(false);
  const [showAccuracy, setShowAccuracy] = useState<boolean>(false);

  const handleScenarioChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const sc = e.target.value;
    setScenario(sc);
    onRefresh(sc, defaultMethod, runRateN);
  };

  const handleMethodChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const meth = e.target.value;
    setDefaultMethod(meth);
  };

  const handleGenerate = () => {
    onRefresh(scenario, defaultMethod, runRateN);
  };

  const handleLock = async () => {
    if (!data?.versionId) return;
    const confirmText = window.confirm(
      `Are you sure you want to permanently lock version "${data.versionId}"?\n\nThis will freeze the current projections, totals, and lines for pack issuance per FR-FC-009.`
    );
    if (!confirmText) return;

    try {
      setLocking(true);
      await onLockVersion(data.versionId);
    } finally {
      setLocking(false);
    }
  };

  const formatMoney = (valStr?: string) => {
    if (!valStr || valStr === '—') return '—';
    const num = parseFloat(valStr);
    return isNaN(num) ? '—' : '₹' + num.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  // Filter lines by search term
  const filteredLines = (data?.lines || []).filter((l) => {
    if (!searchTerm) return true;
    const matchStr = `${l.account_code} ${l.account_name} ${l.statement_line} ${l.method_used}`.toLowerCase();
    return matchStr.includes(searchTerm.toLowerCase());
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      {/* Pinned Workspace Header (SCR-027) */}
      <div
        style={{
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          border: '1px solid #e2e8f0',
          padding: '16px 20px',
          display: 'flex',
          flexDirection: 'column',
          gap: '14px',
          boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
        }}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '10px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <h2 style={{ margin: 0, fontSize: '18px', fontWeight: 600, color: '#0f172a' }}>
                Forecast &bull; FY26
              </h2>
              <span
                style={{
                  padding: '3px 8px',
                  backgroundColor: '#e0f2fe',
                  color: '#0369a1',
                  borderRadius: '12px',
                  fontSize: '12px',
                  fontWeight: 600,
                }}
              >
                P10–P12 Open (P01–P09 Locked Actuals)
              </span>
              {data?.isLocked && (
                <span
                  style={{
                    padding: '3px 8px',
                    backgroundColor: '#fef3c7',
                    color: '#92400e',
                    borderRadius: '12px',
                    fontSize: '12px',
                    fontWeight: 600,
                  }}
                >
                  🔒 Locked Version
                </span>
              )}
            </div>
            <div style={{ fontSize: '12px', color: '#64748b', marginTop: '4px' }}>
              Version: <strong style={{ color: '#0f172a' }}>{data?.versionId || 'FC-FY26-BASE-v1'}</strong> &bull; Generated by{' '}
              {data?.generatedBy || 'Aarti'} ({data?.lastGeneratedAt ? new Date(data.lastGeneratedAt).toLocaleTimeString() : 'Recent'})
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <label style={{ fontSize: '13px', fontWeight: 600, color: '#475569' }}>Scenario:</label>
            <select
              value={scenario}
              onChange={handleScenarioChange}
              style={{
                padding: '6px 12px',
                borderRadius: '6px',
                border: '1px solid #cbd5e1',
                fontSize: '13px',
                fontWeight: 600,
                backgroundColor: '#ffffff',
                color: '#0f172a',
                cursor: 'pointer',
              }}
            >
              <option value="base">Base Case (0%)</option>
              <option value="best">Best Case (+5% Rev / -3% Opex)</option>
              <option value="worst">Worst Case (-5% Rev / +3% Opex)</option>
            </select>

            <button
              onClick={() => setShowCompare(true)}
              style={{
                padding: '6px 12px',
                backgroundColor: '#ffffff',
                border: '1px solid #cbd5e1',
                borderRadius: '6px',
                fontSize: '13px',
                fontWeight: 600,
                color: '#334155',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
              }}
            >
              <span>📊</span> Compare scenarios
            </button>

            <button
              onClick={() => setShowAccuracy(true)}
              style={{
                padding: '6px 12px',
                backgroundColor: '#ffffff',
                border: '1px solid #cbd5e1',
                borderRadius: '6px',
                fontSize: '13px',
                fontWeight: 600,
                color: '#334155',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
              }}
            >
              <span>🎯</span> Accuracy report
            </button>

            <button
              onClick={handleLock}
              disabled={locking || data?.isLocked}
              style={{
                padding: '6px 14px',
                backgroundColor: data?.isLocked ? '#e2e8f0' : '#059669',
                color: data?.isLocked ? '#94a3b8' : '#ffffff',
                border: 'none',
                borderRadius: '6px',
                fontSize: '13px',
                fontWeight: 600,
                cursor: data?.isLocked || locking ? 'not-allowed' : 'pointer',
              }}
            >
              {data?.isLocked ? 'Locked ✓' : locking ? 'Locking...' : 'Lock version ▸'}
            </button>
          </div>
        </div>

        {/* Action Controls & Method Default Row */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingTop: '10px',
            borderTop: '1px solid #f1f5f9',
            flexWrap: 'wrap',
            gap: '10px',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <span style={{ fontSize: '13px', color: '#475569' }}>Default Method:</span>
            <select
              value={defaultMethod}
              onChange={handleMethodChange}
              style={{
                padding: '5px 10px',
                borderRadius: '6px',
                border: '1px solid #cbd5e1',
                fontSize: '12px',
                backgroundColor: '#ffffff',
              }}
            >
              <option value="run_rate">Run-rate (Trailing N periods)</option>
              <option value="remaining_budget">Remaining Budget Spread</option>
              <option value="avg_3m">3-Month Trailing Average</option>
            </select>

            {defaultMethod === 'run_rate' && (
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <span style={{ fontSize: '12px', color: '#64748b' }}>N =</span>
                <select
                  value={runRateN}
                  onChange={(e) => setRunRateN(Number(e.target.value))}
                  style={{
                    padding: '4px 8px',
                    borderRadius: '4px',
                    border: '1px solid #cbd5e1',
                    fontSize: '12px',
                  }}
                >
                  <option value={1}>1 period</option>
                  <option value={3}>3 periods</option>
                  <option value={6}>6 periods</option>
                  <option value={9}>9 periods</option>
                </select>
              </div>
            )}

            <button
              onClick={handleGenerate}
              disabled={loading}
              style={{
                padding: '6px 14px',
                backgroundColor: '#0284c7',
                color: '#ffffff',
                border: 'none',
                borderRadius: '6px',
                fontSize: '13px',
                fontWeight: 600,
                cursor: loading ? 'not-allowed' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
              }}
            >
              <span>{loading ? 'Refreshing...' : 'Generate ▸'}</span>
            </button>
          </div>

          <div>
            <input
              type="text"
              placeholder="Search account code, name, or method..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{
                padding: '6px 12px',
                borderRadius: '6px',
                border: '1px solid #cbd5e1',
                fontSize: '12px',
                width: '260px',
              }}
            />
          </div>
        </div>
      </div>

      {/* SCR-027 Guidance Banner */}
      <div
        style={{
          padding: '12px 16px',
          backgroundColor: '#eff6ff',
          border: '1px solid #bfdbfe',
          borderRadius: '8px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontSize: '12px',
          color: '#1e40af',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <span style={{ fontSize: '16px' }}>ⓘ</span>
          <div>
            <strong>Guidance (SCR-027):</strong> <code>avg_3m</code> showed smaller error than <code>run_rate</code> for "Revenue" over 3 closed periods. Manual overrides require audited reason per CALC-064.
          </div>
        </div>
        <button
          onClick={() => {
            setDefaultMethod('avg_3m');
            onRefresh(scenario, 'avg_3m', runRateN);
          }}
          style={{
            padding: '5px 12px',
            backgroundColor: '#ffffff',
            border: '1px solid #93c5fd',
            borderRadius: '6px',
            color: '#1d4ed8',
            fontSize: '12px',
            fontWeight: 600,
            cursor: 'pointer',
          }}
        >
          Apply to these lines
        </button>
      </div>

      {/* Forecast Data Grid */}
      <div
        style={{
          backgroundColor: '#ffffff',
          borderRadius: '8px',
          border: '1px solid #e2e8f0',
          overflow: 'hidden',
          boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
        }}
      >
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
          <thead>
            <tr style={{ backgroundColor: '#f8fafc', borderBottom: '2px solid #e2e8f0' }}>
              <th style={{ textAlign: 'left', padding: '12px 14px', fontWeight: 600, color: '#475569' }}>Account</th>
              <th style={{ textAlign: 'left', padding: '12px 14px', fontWeight: 600, color: '#475569' }}>Method</th>
              <th style={{ textAlign: 'right', padding: '12px 14px', fontWeight: 600, color: '#0369a1' }}>
                P10 (Open)
              </th>
              <th style={{ textAlign: 'right', padding: '12px 14px', fontWeight: 600, color: '#0369a1' }}>
                P11 (Open)
              </th>
              <th style={{ textAlign: 'right', padding: '12px 14px', fontWeight: 600, color: '#0369a1' }}>
                P12 (Open)
              </th>
              <th style={{ textAlign: 'right', padding: '12px 14px', fontWeight: 600, color: '#0f172a' }}>
                FY Landing (P01–P12)
              </th>
              <th style={{ textAlign: 'center', padding: '12px 14px', fontWeight: 600, color: '#475569' }}>
                Override
              </th>
            </tr>
          </thead>
          <tbody>
            {loading && !data ? (
              <tr>
                <td colSpan={7} style={{ textAlign: 'center', padding: '40px', color: '#64748b' }}>
                  Loading forecast lines...
                </td>
              </tr>
            ) : filteredLines.length === 0 ? (
              <tr>
                <td colSpan={7} style={{ textAlign: 'center', padding: '40px', color: '#64748b' }}>
                  No accounts found matching filter.
                </td>
              </tr>
            ) : (
              filteredLines.map((line) => {
                const isOverridden = line.is_manual_override;
                return (
                  <tr
                    key={line.account_id}
                    style={{
                      borderBottom: '1px solid #f1f5f9',
                      backgroundColor: isOverridden ? '#fffbeb' : '#ffffff',
                    }}
                  >
                    <td style={{ padding: '10px 14px' }}>
                      <div style={{ fontWeight: 600, color: '#0f172a' }}>
                        <span style={{ fontFamily: 'monospace', color: '#0284c7', marginRight: '6px' }}>
                          {line.account_code}
                        </span>
                        {line.account_name}
                      </div>
                      <div style={{ fontSize: '11px', color: '#64748b' }}>
                        {line.statement_line} &bull; {line.account_group}
                      </div>
                    </td>

                    <td style={{ padding: '10px 14px' }}>
                      {isOverridden ? (
                        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                          <span
                            style={{
                              padding: '2px 8px',
                              backgroundColor: '#fef3c7',
                              color: '#b45309',
                              borderRadius: '4px',
                              fontSize: '12px',
                              fontWeight: 600,
                            }}
                          >
                            manual ⚑
                          </span>
                          {line.override_reason && (
                            <span
                              title={line.override_reason}
                              style={{
                                fontSize: '11px',
                                color: '#92400e',
                                maxWidth: '120px',
                                overflow: 'hidden',
                                textOverflow: 'ellipsis',
                                whiteSpace: 'nowrap',
                              }}
                            >
                              ({line.override_reason})
                            </span>
                          )}
                        </div>
                      ) : !line.is_eligible ? (
                        <span
                          title={line.ineligibility_reason || 'Excluded line'}
                          style={{
                            padding: '2px 8px',
                            backgroundColor: '#f1f5f9',
                            color: '#64748b',
                            borderRadius: '4px',
                            fontSize: '12px',
                          }}
                        >
                          not forecast ⓘ
                        </span>
                      ) : (
                        <span
                          style={{
                            padding: '2px 8px',
                            backgroundColor: '#f0f9ff',
                            color: '#0369a1',
                            borderRadius: '4px',
                            fontSize: '12px',
                            fontWeight: 500,
                          }}
                        >
                          {line.method_used}
                        </span>
                      )}
                    </td>

                    <td style={{ padding: '10px 14px', textAlign: 'right', fontFamily: 'monospace', fontWeight: 500 }}>
                      {formatMoney(line.period_amounts['FY26-P10'])}
                    </td>

                    <td style={{ padding: '10px 14px', textAlign: 'right', fontFamily: 'monospace', fontWeight: 500 }}>
                      {formatMoney(line.period_amounts['FY26-P11'])}
                    </td>

                    <td style={{ padding: '10px 14px', textAlign: 'right', fontFamily: 'monospace', fontWeight: 500 }}>
                      {formatMoney(line.period_amounts['FY26-P12'])}
                    </td>

                    <td
                      style={{
                        padding: '10px 14px',
                        textAlign: 'right',
                        fontFamily: 'monospace',
                        fontWeight: 700,
                        color: '#0f172a',
                      }}
                    >
                      {formatMoney(line.fy_landing)}
                    </td>

                    <td style={{ padding: '10px 14px', textAlign: 'center' }}>
                      <button
                        title="Manually override forecast cell"
                        onClick={() =>
                          setOverrideTarget({
                            line,
                            periodCode: 'FY26-P10',
                            amount: line.period_amounts['FY26-P10'] || '0.00',
                          })
                        }
                        style={{
                          background: 'none',
                          border: '1px solid #cbd5e1',
                          borderRadius: '4px',
                          padding: '4px 8px',
                          fontSize: '12px',
                          cursor: 'pointer',
                          color: '#475569',
                        }}
                      >
                        ⚙️ Override
                      </button>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>

          {/* Grand Totals Footer */}
          {data?.totals && (
            <tfoot>
              <tr style={{ backgroundColor: '#f8fafc', borderTop: '2px solid #cbd5e1' }}>
                <td colSpan={2} style={{ padding: '12px 14px', fontWeight: 700, color: '#0f172a' }}>
                  Total Company Landing
                </td>
                <td style={{ padding: '12px 14px', textAlign: 'right', fontFamily: 'monospace', fontWeight: 700 }}>
                  {formatMoney(data.totals['FY26-P10'])}
                </td>
                <td style={{ padding: '12px 14px', textAlign: 'right', fontFamily: 'monospace', fontWeight: 700 }}>
                  {formatMoney(data.totals['FY26-P11'])}
                </td>
                <td style={{ padding: '12px 14px', textAlign: 'right', fontFamily: 'monospace', fontWeight: 700 }}>
                  {formatMoney(data.totals['FY26-P12'])}
                </td>
                <td
                  style={{
                    padding: '12px 14px',
                    textAlign: 'right',
                    fontFamily: 'monospace',
                    fontWeight: 800,
                    color: '#0284c7',
                  }}
                >
                  {formatMoney(data.totals['fy_landing'])}
                </td>
                <td></td>
              </tr>
            </tfoot>
          )}
        </table>
      </div>

      {/* Manual Override Modal */}
      {overrideTarget && (
        <ManualOverrideModal
          line={overrideTarget.line}
          periodCode={overrideTarget.periodCode}
          currentAmount={overrideTarget.amount}
          onClose={() => setOverrideTarget(null)}
          onSubmit={onOverrideSubmit}
        />
      )}

      {/* Scenario Compare Modal */}
      {showCompare && (
        <ForecastCompareModal
          sessionToken={sessionToken}
          onClose={() => setShowCompare(false)}
        />
      )}

      {/* Accuracy Report Modal */}
      {showAccuracy && (
        <ForecastAccuracyModal
          sessionToken={sessionToken}
          onClose={() => setShowAccuracy(false)}
        />
      )}
    </div>
  );
};
