"""Central error catalog module serving the error catalog per docs 26 (§5) and docs 08 (§16).

Quoted from docs/26_API_CONTRACT.md §5 & docs/08_UI_UX_SPEC.md §16:
- All error responses MUST adhere to the standardized error envelope containing `code`, `userMessage`, and `hint`.
- `GET /meta/error-catalog` is the runtime projection of this section: `{code, slug, severity, message, hint, httpStatus, ownerDoc}`.
- Error Message Catalog (SCR-041): Every user-facing error must display its error code, clear explanation, and troubleshooting hint.
"""

from __future__ import annotations

from typing import List, Dict, Any


ERROR_CATALOG: List[Dict[str, Any]] = [
    # VAL family
    {
        "code": "ERR-VAL-001",
        "family": "VAL",
        "httpStatus": 400,
        "message": "Typed confirmation missing or mismatched (project name, reopen reason)",
        "hint": "Type the name exactly as shown to confirm.",
        "slug": "val.typedConfirmationMismatch",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-VAL-002",
        "family": "VAL",
        "httpStatus": 400,
        "message": "A required field for this action is missing",
        "hint": "Complete the highlighted field and try again.",
        "slug": "val.missingRequiredField",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-VAL-003",
        "family": "VAL",
        "httpStatus": 400,
        "message": "Invalid enum/date/period/amount, or an unsupported filter/sort field",
        "hint": "Reload the view; the app will use valid values.",
        "slug": "val.invalidValue",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-VAL-004",
        "family": "VAL",
        "httpStatus": 400,
        "message": "Value outside the allowed range (threshold, page size, materiality override)",
        "hint": "Enter a value within the range shown next to the field.",
        "slug": "val.outOfRange",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    # BVA family
    {
        "code": "ERR-BVA-001",
        "family": "BVA",
        "httpStatus": 404,
        "message": "No data for the requested period/window",
        "hint": "Import that period's files, or choose another window.",
        "slug": "bva.noData",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-BVA-002",
        "family": "BVA",
        "httpStatus": 409,
        "message": "Comparability guard: prior-year/TTM comparison unavailable",
        "hint": "Show the view without the comparison, or import the missing period.",
        "slug": "bva.comparabilityGuard",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-BVA-003",
        "family": "BVA",
        "httpStatus": 400,
        "message": "Unsupported grain/rollup combination for this view",
        "hint": "Choose a supported grain for this view.",
        "slug": "bva.unsupportedGrain",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-BVA-004",
        "family": "BVA",
        "httpStatus": 409,
        "message": "Drill target is ambiguous (more than one figure matches)",
        "hint": "Pick the exact figure you want to drill into.",
        "slug": "bva.ambiguousDrill",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    # FC family
    {
        "code": "ERR-FC-001",
        "family": "FC",
        "httpStatus": 409,
        "message": "No eligible history for the chosen method",
        "hint": "Choose another method, or extend the history.",
        "slug": "fc.noEligibleHistory",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-FC-002",
        "family": "FC",
        "httpStatus": 409,
        "message": "Forecast version is locked",
        "hint": "Copy the version to edit it.",
        "slug": "fc.versionLocked",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-FC-003",
        "family": "FC",
        "httpStatus": 404,
        "message": "Scenario or version not found",
        "hint": "Pick an existing scenario from the list.",
        "slug": "fc.scenarioNotFound",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-FC-004",
        "family": "FC",
        "httpStatus": 400,
        "message": "Manual override has no reason",
        "hint": "Add a short reason for the override.",
        "slug": "fc.overrideReasonRequired",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    # RUL family
    {
        "code": "ERR-RUL-001",
        "family": "RUL",
        "httpStatus": 404,
        "message": "Rule not found",
        "hint": "Reload the rule catalogue.",
        "slug": "rul.ruleNotFound",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-RUL-002",
        "family": "RUL",
        "httpStatus": 409,
        "message": "A rule run is already in progress",
        "hint": "Wait for the current run to finish.",
        "slug": "rul.runInProgress",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-RUL-003",
        "family": "RUL",
        "httpStatus": 200,
        "message": "Rule auto-disabled: required master data is missing",
        "hint": "Load the missing master data, then re-run.",
        "slug": "rul.ruleAutoDisabled",
        "severity": "Low",
        "ownerDoc": "02/26",
    },
    # STO family
    {
        "code": "ERR-STO-001",
        "family": "STO",
        "httpStatus": 404,
        "message": "Project not found",
        "hint": "Open it from the project list.",
        "slug": "sto.projectNotFound",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-002",
        "family": "STO",
        "httpStatus": 409,
        "message": "Project is open in another window (single-instance mutex)",
        "hint": "Bring that window forward, or close it and retry.",
        "slug": "sto.projectLocked",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-003",
        "family": "STO",
        "httpStatus": 400,
        "message": "Project path invalid or not writable",
        "hint": "Choose a folder under your user profile that you can write to.",
        "slug": "sto.invalidPath",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-004",
        "family": "STO",
        "httpStatus": 409,
        "message": "A project already exists at that path",
        "hint": "Open it instead, or choose another folder.",
        "slug": "sto.projectExists",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-005",
        "family": "STO",
        "httpStatus": 404,
        "message": "Period not found",
        "hint": "Pick a period from the list.",
        "slug": "sto.periodNotFound",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-006",
        "family": "STO",
        "httpStatus": 409,
        "message": "Write attempted on a closed period",
        "hint": "Reopen the period (audited) or use the open period.",
        "slug": "sto.periodClosed",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-007",
        "family": "STO",
        "httpStatus": 409,
        "message": "Period is already closed",
        "hint": "Continue with the next period.",
        "slug": "sto.periodAlreadyClosed",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-008",
        "family": "STO",
        "httpStatus": 400,
        "message": "Backup zip invalid or incompatible",
        "hint": "Choose a backup made by this app; nothing was changed.",
        "slug": "sto.invalidBackup",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-009",
        "family": "STO",
        "httpStatus": 409,
        "message": "Restore target folder is not empty",
        "hint": "Choose an empty folder; nothing was changed.",
        "slug": "sto.restoreTargetNotEmpty",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-010",
        "family": "STO",
        "httpStatus": 404,
        "message": "Versioned artefact or version not found",
        "hint": "Pick a version from the history list.",
        "slug": "sto.versionNotFound",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-011",
        "family": "STO",
        "httpStatus": 409,
        "message": "Revert blocked by a dependent artefact",
        "hint": "Revert the dependent item first; nothing was changed.",
        "slug": "sto.revertBlocked",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-012",
        "family": "STO",
        "httpStatus": 404,
        "message": "Archived source file is missing from the archive",
        "hint": "Re-import the file; the rest of the project is unaffected.",
        "slug": "sto.archivedFileMissing",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-013",
        "family": "STO",
        "httpStatus": 400,
        "message": "Delete confirmation name mismatch",
        "hint": "Type the project name exactly to confirm deletion.",
        "slug": "sto.deleteConfirmationMismatch",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-014",
        "family": "STO",
        "httpStatus": 409,
        "message": "Free space below the working threshold",
        "hint": "Free space or archive raw files before continuing.",
        "slug": "sto.lowDiskSpace",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-STO-015",
        "family": "STO",
        "httpStatus": 400,
        "message": "Sample-project conversion confirmation missing",
        "hint": "Tick the conversion confirmation and retry.",
        "slug": "sto.sampleConversionMissing",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    # AI family
    {
        "code": "ERR-AI-001",
        "family": "AI",
        "httpStatus": 409,
        "message": "AI is off or keyless",
        "hint": "Turn AI on in Settings, or use the rule-based version.",
        "slug": "ai.keylessOrOff",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-AI-002",
        "family": "AI",
        "httpStatus": 400,
        "message": "Payload would exceed the redaction or token cap policy",
        "hint": "Narrow the scope, or use the rule-based version.",
        "slug": "ai.tokenCapExceeded",
        "severity": "High",
        "ownerDoc": "02/26",
    },
    {
        "code": "ERR-AI-003",
        "family": "AI",
        "httpStatus": 409,
        "message": "Draft is already approved (immutable)",
        "hint": "Create a new draft; approved text stays in history.",
        "slug": "ai.draftAlreadyApproved",
        "severity": "Medium",
        "ownerDoc": "02/26",
    },
    # IMP family (IMP-001 to IMP-032)
    {
        "code": "ERR-IMP-001",
        "family": "IMP",
        "httpStatus": 400,
        "message": "File readable and format supported",
        "hint": "Provide a readable file in a supported format.",
        "slug": "import.unreadableFile",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-002",
        "family": "IMP",
        "httpStatus": 400,
        "message": "File size within the configured limit",
        "hint": "Reduce file size or confirm large file import.",
        "slug": "import.fileTooLarge",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-003",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Row count within the configured limit",
        "hint": "Confirm large row count import.",
        "slug": "import.rowLimitExceeded",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-004",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Header row detected",
        "hint": "User must pick the header row.",
        "slug": "import.noHeaderDetected",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-005",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Required columns present after mapping",
        "hint": "Map all required columns.",
        "slug": "import.missingRequiredColumns",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-006",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Duplicate column headers resolved",
        "hint": "Rename or ignore duplicate headers.",
        "slug": "import.duplicateHeaders",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-007",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Expected sheet present (per profile)",
        "hint": "Pick the correct sheet or cancel.",
        "slug": "import.sheetNotFound",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-008",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Data range not empty",
        "hint": "Ensure data range contains rows or apply zero-activity override.",
        "slug": "import.noDataRows",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-009",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Workbook not encrypted / not unreadable",
        "hint": "Remove encryption from the file.",
        "slug": "import.encryptedFile",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-010",
        "family": "IMP",
        "httpStatus": 400,
        "message": "All required canonical fields mapped",
        "hint": "Complete mapping for all required canonical fields.",
        "slug": "import.mappingIncomplete",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-011",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Unmapped-row share below 90%",
        "hint": "Review mapping suggestions to increase coverage above 90%.",
        "slug": "import.unmappedThreshold",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-012",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Dimension-string tokens parsed",
        "hint": "Quarantined row: review dimension string syntax.",
        "slug": "import.dimensionUnparsed",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-013",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Unknown/unmapped account codes",
        "hint": "Map unknown account codes using mapping suggestions.",
        "slug": "import.unknownAccounts",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-014",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Date values parsed",
        "hint": "Quarantined row: fix invalid date format.",
        "slug": "import.dateUnparsed",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-015",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Ambiguous date formats confirmed",
        "hint": "Confirm date format choice for profile.",
        "slug": "import.ambiguousDate",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-016",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Numeric values parsed",
        "hint": "Quarantined row: correct non-numeric amount.",
        "slug": "import.numberUnparsed",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-017",
        "family": "IMP",
        "httpStatus": 200,
        "message": "Sign / Cr-Dr interpretation applied",
        "hint": "Review interpreted direction.",
        "slug": "import.signRuleApplied",
        "severity": "Low",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-018",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Period resolved against the fiscal calendar",
        "hint": "Quarantined row: ensure transaction date falls within fiscal calendar.",
        "slug": "import.periodNotInCalendar",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-019",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Dates inside the configured fiscal year",
        "hint": "Quarantined row: adjust transaction date to current fiscal year.",
        "slug": "import.dateOutsideFiscalYear",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-020",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Currency matches the project currency",
        "hint": "Quarantined row: ensure currency matches project currency.",
        "slug": "import.mixedCurrency",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-021",
        "family": "IMP",
        "httpStatus": 200,
        "message": "Zero-amount rows noted",
        "hint": "Zero-amount rows kept and flagged.",
        "slug": "import.zeroAmountRows",
        "severity": "Low",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-022",
        "family": "IMP",
        "httpStatus": 200,
        "message": "Debit and credit not both populated",
        "hint": "Verify single-sided entry.",
        "slug": "import.bothDebitCredit",
        "severity": "Low",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-023",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Debit = credit within tolerance, per file/entity/period",
        "hint": "Review balance imbalance amount and contributing rows.",
        "slug": "import.balanceMismatch",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-024",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Row-count reconciliation (source = loaded + quarantined + rejected)",
        "hint": "Internal invariant check failed; contact support.",
        "slug": "import.countMismatch",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-025",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Control-total variance within tolerance",
        "hint": "Provide valid control totals or record acceptance.",
        "slug": "import.controlTotalVariance",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-026",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Budget sum matches the approved total",
        "hint": "Adjust budget import or record acceptance.",
        "slug": "import.approvedTotalVariance",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-027",
        "family": "IMP",
        "httpStatus": 200,
        "message": "Within-file duplicate candidates reported",
        "hint": "Review reported duplicate candidates.",
        "slug": "import.duplicateCandidates",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-028",
        "family": "IMP",
        "httpStatus": 200,
        "message": "Cross-batch duplicate candidates reported",
        "hint": "Choose skip, import anyway, or cancel.",
        "slug": "import.crossBatchDuplicates",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-029",
        "family": "IMP",
        "httpStatus": 400,
        "message": "File checksum not previously committed",
        "hint": "File was already imported on previous date; use unique file.",
        "slug": "import.alreadyImported",
        "severity": "High",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-030",
        "family": "IMP",
        "httpStatus": 200,
        "message": "Inactive cost centre usage noted",
        "hint": "Review inactive cost centre rows.",
        "slug": "import.inactiveCostCentre",
        "severity": "Low",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-031",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Budget coverage matrix reported",
        "hint": "Import missing entity x account x period cells.",
        "slug": "import.budgetCoverageGap",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    {
        "code": "ERR-IMP-032",
        "family": "IMP",
        "httpStatus": 400,
        "message": "Budget/forecast duplicate lines on the uniqueness key",
        "hint": "Resolve conflicting duplicate budget lines.",
        "slug": "import.duplicateBudgetLines",
        "severity": "Medium",
        "ownerDoc": "04/26",
    },
    # EXP family (Doc 11 / Doc 12)
    {
        "code": "ERR-EXP-002",
        "family": "EXP",
        "httpStatus": 409,
        "message": "The destination file is locked by another program.",
        "hint": "Close the file in PowerPoint/Excel and try again.",
        "slug": "exp.fileLocked",
        "severity": "High",
        "ownerDoc": "11/26",
    },
    {
        "code": "ERR-EXP-003",
        "family": "EXP",
        "httpStatus": 507,
        "message": "Disk is full.",
        "hint": "Free up space on your device.",
        "slug": "exp.diskFull",
        "severity": "High",
        "ownerDoc": "11/26",
    },
    {
        "code": "ERR-EXP-006",
        "family": "EXP",
        "httpStatus": 499,
        "message": "Export was cancelled by the user.",
        "hint": "No action needed.",
        "slug": "exp.cancelled",
        "severity": "Low",
        "ownerDoc": "11/26",
    },
    {
        "code": "ERR-EXP-007",
        "family": "EXP",
        "httpStatus": 409,
        "message": "Underlying data changed during generation.",
        "hint": "Retry the export.",
        "slug": "exp.dataChanged",
        "severity": "High",
        "ownerDoc": "11/26",
    },
    {
        "code": "ERR-EXP-009",
        "family": "EXP",
        "httpStatus": 500,
        "message": "Export target is a synced cloud path that is currently offline or unreachable.",
        "hint": "Save to a local folder instead, or reconnect to the network.",
        "slug": "exp.syncedPathUnreachable",
        "severity": "High",
        "ownerDoc": "11/26",
    },
    {
        "code": "ERR-EXP-012",
        "family": "EXP",
        "httpStatus": 400,
        "message": "Some slides in your deck don't have a place for the required content.",
        "hint": "Map the shapes, or use the built-in deck for the affected slides",
        "slug": "exp.missingLayoutsOrShapes",
        "severity": "High",
        "ownerDoc": "12/26",
    },
    {
        "code": "ERR-EXP-013",
        "family": "EXP",
        "httpStatus": 400,
        "message": "A slide can't fit its required figures — this is a layout problem, not a data problem.",
        "hint": "Copy details and report it; the layout/template must change",
        "slug": "exp.cannotFitRequiredFigures",
        "severity": "High",
        "ownerDoc": "12/26",
    },
    {
        "code": "ERR-EXP-014",
        "family": "EXP",
        "httpStatus": 500,
        "message": "The deck template is missing or damaged.",
        "hint": "Reinstall/repair the app (the template ships with it); report if it recurs",
        "slug": "exp.templateMissingOrDamaged",
        "severity": "Critical",
        "ownerDoc": "12/26",
    },
    {
        "code": "ERR-EXP-015",
        "family": "EXP",
        "httpStatus": 200,
        "message": "The bridge is being drawn with the alternate (stacked) method.",
        "hint": "None — the fallback is automatic and recorded; report only if it appears in a release build",
        "slug": "exp.alternateBridgeMethod",
        "severity": "Medium",
        "ownerDoc": "12/26",
    },
    {
        "code": "ERR-EXP-016",
        "family": "EXP",
        "httpStatus": 400,
        "message": "Your logo couldn't be added to the deck.",
        "hint": "Re-select the logo in Settings -> Branding",
        "slug": "exp.logoExtractionFailed",
        "severity": "Medium",
        "ownerDoc": "12/26",
    },
    {
        "code": "ERR-EXP-017",
        "family": "EXP",
        "httpStatus": 500,
        "message": "A chart's data couldn't be embedded, so the deck was not written.",
        "hint": "Retry; if it recurs, report it (charts must stay editable — an image chart is never a substitute)",
        "slug": "exp.chartDataEmbeddingFailed",
        "severity": "High",
        "ownerDoc": "12/26",
    },
    {
        "code": "ERR-EXP-018",
        "family": "EXP",
        "httpStatus": 400,
        "message": "This deck is too large to generate (<size>).",
        "hint": "Drop the preserved appendix slides, or use the built-in deck",
        "slug": "exp.deckSizeLimitExceeded",
        "severity": "High",
        "ownerDoc": "12/26",
    },
]


def get_error_catalog() -> List[Dict[str, Any]]:
    """Return the full centralized error catalog."""
    return ERROR_CATALOG
