"""Period lifecycle repository managing period status, new-period wizard, close snapshots, and audited reopen.

Per docs/02_FUNCTIONAL_SPEC.md:
- FR-PRJ-004: New Period wizard (open period, source-load checklist, carry forward mappings/assumptions never numbers).
- FR-PRJ-005: Period close with immutable snapshot + typed reopen (audited).
- FR-PRJ-010: Period-close snapshot.
- FR-PRJ-003: Period status indicators / open/closed periods.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from app.engine.store.db import DatabaseManager


@dataclass
class PeriodDTO:
    period_id: int
    fiscal_year: int
    period_number: int
    period_code: str
    period_label: str
    start_date: str
    end_date: str
    status: str  # 'open' or 'closed'
    has_actuals: bool
    has_budget: bool
    is_forecast_eligible: bool
    closed_at: Optional[str] = None
    created_at: Optional[str] = None


class PeriodRepository:
    """Repository managing period lifecycle in DuckDB."""

    def __init__(self, db_manager: DatabaseManager):
        self.db = db_manager
        self._ensure_tables()

    @staticmethod
    def _next_id(duck_conn: Any, table: str, column: str) -> int:
        """Allocate the next primary key for a DuckDB table.

        WHY THIS EXISTS. DuckDB 1.5.6 has no auto-increment column, verified
        against this project's own duckdb build:

        - `INTEGER PRIMARY KEY` does NOT self-assign. Omitting the column
          raises `NOT NULL constraint failed: <table>.<column>`.
        - `GENERATED ALWAYS AS IDENTITY` / `GENERATED BY DEFAULT AS IDENTITY`
          raise `NotImplementedException: Constraint not implemented!`.
        - `AUTOINCREMENT` is a parser error - that is SQLite syntax, which is
          why the working `MappingSuggestionAudit` (schema_sqlite.sql:237)
          can use it while these DuckDB tables cannot.

        So every DuckDB key in this codebase is supplied explicitly, and this
        helper is how these three methods do it: `db.py:90` seeds DimPeriod with
        an explicit `period_id`, and `ImportRepository.commit_budget_replace`
        computes `budget_id` in Python the same way.

        `table` and `column` are internal literals from this module, never
        caller-supplied. The read-then-write is safe under the ADR-004
        single-user desktop model: DuckDB permits one writing process per file.
        """
        row = duck_conn.execute(
            f"SELECT COALESCE(MAX({column}), 0) + 1 FROM {table}"
        ).fetchone()
        return int(row[0])

    def _ensure_tables(self) -> None:
        duck_conn = self.db.get_duckdb_connection()
        duck_conn.execute("""
            CREATE TABLE IF NOT EXISTS PeriodSnapshot (
                snapshot_id INTEGER PRIMARY KEY,
                period_id INTEGER NOT NULL,
                snapshot_json TEXT NOT NULL,
                snapshot_hash VARCHAR(64) NOT NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        """)
        duck_conn.execute("""
            CREATE TABLE IF NOT EXISTS PeriodAuditLog (
                log_id INTEGER PRIMARY KEY,
                period_id INTEGER NOT NULL,
                action VARCHAR(20) NOT NULL,
                reason TEXT,
                performed_by VARCHAR(100),
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        """)

    def list_periods(self) -> List[PeriodDTO]:
        duck_conn = self.db.get_duckdb_connection()
        rows = duck_conn.execute("""
            SELECT period_id, fiscal_year, period_number, period_code, period_label,
                   start_date, end_date, status, has_actuals, has_budget,
                   is_forecast_eligible, closed_at, created_at
            FROM DimPeriod
            ORDER BY fiscal_year ASC, period_number ASC
        """).fetchall()

        result = []
        for r in rows:
            result.append(PeriodDTO(
                period_id=r[0],
                fiscal_year=r[1],
                period_number=r[2],
                period_code=r[3],
                period_label=r[4],
                start_date=str(r[5]),
                end_date=str(r[6]),
                status=r[7],
                has_actuals=bool(r[8]),
                has_budget=bool(r[9]),
                is_forecast_eligible=bool(r[10]),
                closed_at=str(r[11]) if r[11] else None,
                created_at=str(r[12]) if r[12] else None,
            ))
        return result

    def get_period(self, period_id: int) -> Optional[PeriodDTO]:
        periods = self.list_periods()
        for p in periods:
            if p.period_id == period_id:
                return p
        return None

    def open_period(self, fiscal_year: int, period_number: int, period_code: str, period_label: str, start_date: str, end_date: str, carry_forward_config: Dict[str, Any]) -> PeriodDTO:
        duck_conn = self.db.get_duckdb_connection()
        # Insert or update period.
        # period_id is supplied explicitly (see _next_id): omitting it raises
        # `NOT NULL constraint failed: DimPeriod.period_id` whenever
        # period_code is NOT already present. For a period_code that does exist
        # the ON CONFLICT branch discards this value, which is why the New
        # Period wizard used to appear to work for seeded FY26 periods and only
        # fail for a genuinely new fiscal year.
        period_id = self._next_id(duck_conn, "DimPeriod", "period_id")
        duck_conn.execute("""
            INSERT INTO DimPeriod (period_id, fiscal_year, period_number, period_code, period_label, start_date, end_date, status, has_actuals, has_budget, is_forecast_eligible)
            VALUES (?, ?, ?, ?, ?, ?, ?, 'open', FALSE, FALSE, TRUE)
            ON CONFLICT (period_code) DO UPDATE SET
                status = 'open',
                start_date = excluded.start_date,
                end_date = excluded.end_date
        """, [period_id, fiscal_year, period_number, period_code, period_label, start_date, end_date])

        # Record audit log for opening / wizard execution
        row = duck_conn.execute("SELECT period_id FROM DimPeriod WHERE period_code = ?", [period_code]).fetchone()
        period_id = row[0] if row else period_id

        duck_conn.execute("""
            INSERT INTO PeriodAuditLog (log_id, period_id, action, reason, performed_by)
            VALUES (?, ?, 'open_wizard', ?, 'system')
        """, [self._next_id(duck_conn, "PeriodAuditLog", "log_id"),
              period_id, json.dumps(carry_forward_config)])

        return self.get_period(period_id)  # type: ignore

    def close_period(self, period_id: int, closed_by: str = "system") -> PeriodDTO:
        duck_conn = self.db.get_duckdb_connection()
        period = self.get_period(period_id)
        if not period:
            raise ValueError(f"Period {period_id} not found")

        now_str = datetime.now(timezone.utc).isoformat()

        # Capture immutable snapshot of actuals/budget totals for this period.
        # FactActual has no `amount` column (03 DATA_DICTIONARY: it stores
        # debit, credit and the derived net_amount), so selecting SUM(amount)
        # raised `Binder Error: Referenced column "amount" not found` and made
        # close unreachable. net_amount is the amount column for this fact.
        summary_rows = duck_conn.execute("""
            SELECT account_id, SUM(net_amount) as total_amount
            FROM FactActual
            WHERE period_id = ?
            GROUP BY account_id
        """, [period_id]).fetchall()

        snapshot_data = {
            "period_code": period.period_code,
            "closed_at": now_str,
            "totals": {str(r[0]): str(r[1]) for r in summary_rows}
        }
        snapshot_json = json.dumps(snapshot_data, sort_keys=True)
        import hashlib
        snapshot_hash = hashlib.sha256(snapshot_json.encode("utf-8")).hexdigest()

        duck_conn.execute("""
            INSERT INTO PeriodSnapshot (snapshot_id, period_id, snapshot_json, snapshot_hash)
            VALUES (?, ?, ?, ?)
        """, [self._next_id(duck_conn, "PeriodSnapshot", "snapshot_id"),
              period_id, snapshot_json, snapshot_hash])

        duck_conn.execute("""
            UPDATE DimPeriod
            SET status = 'closed', closed_at = CURRENT_TIMESTAMP
            WHERE period_id = ?
        """, [period_id])

        duck_conn.execute("""
            INSERT INTO PeriodAuditLog (log_id, period_id, action, reason, performed_by)
            VALUES (?, ?, 'close', 'Period closed and immutable snapshot captured', ?)
        """, [self._next_id(duck_conn, "PeriodAuditLog", "log_id"), period_id, closed_by])

        return self.get_period(period_id)  # type: ignore

    def reopen_period(self, period_id: int, reason: str, reopened_by: str) -> PeriodDTO:
        duck_conn = self.db.get_duckdb_connection()
        period = self.get_period(period_id)
        if not period:
            raise ValueError(f"Period {period_id} not found")

        if not reason or len(reason.strip()) < 5:
            raise ValueError("Typed reopen requires a valid audit reason (minimum 5 characters)")

        duck_conn.execute("""
            UPDATE DimPeriod
            SET status = 'open', closed_at = NULL
            WHERE period_id = ?
        """, [period_id])

        duck_conn.execute("""
            INSERT INTO PeriodAuditLog (log_id, period_id, action, reason, performed_by)
            VALUES (?, ?, 'reopen', ?, ?)
        """, [self._next_id(duck_conn, "PeriodAuditLog", "log_id"),
              period_id, reason, reopened_by])

        return self.get_period(period_id)  # type: ignore
