"""Assign the two verification-orphaned handoffs.

TB-006 (HO-036) and TB-011 (HO-038) were authored by `freebuff2`. `team.py verify` requires a
different agent, and the rotation refuses the author, so these two cannot be verified by anyone in
their own lane. Left alone they wait forever - which is how 8 of `antigravity`'s handoffs got to a
7-hour median. Assigning them explicitly is the only way they move.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TITLE = (
    "Verify the two handoffs nobody can verify from their own lane. TB-006 (handoff HO-036) and "
    "TB-011 (handoff HO-038) were authored by freebuff2, and verification may not be done by the "
    "author - so the rotation can never assign them and they would otherwise wait indefinitely. That "
    "is not hypothetical: eight of antigravity's handoffs have been sitting at a 7-hour median for "
    "exactly this reason, with the seat now AWAY. Verify these two. Both are corpus work, so the "
    "substance to check is: the corpus is regenerated by ONE command from a manifest, the same seed "
    "gives byte-identical output, and the numbers in the reports are recomputed rather than "
    "transcribed. Acceptance: both carry a `### Verified by` block naming an agent who is not "
    "freebuff2, each stating what was re-run plus the raw output; anything that does not reproduce is "
    "rejected with the command that failed rather than softened."
)

MSGS = [
    ("opencode",
     "One more, and it is deliberately not in your main stream.\n\n"
     "  VERIFY-03 [P1]  verify TB-006 (HO-036) and TB-011 (HO-038)\n\n"
     "Both were authored by freebuff2, and verification cannot be done by the author - so the "
     "rotation can never assign them and they would wait forever. Eight of antigravity's handoffs "
     "are stuck at a 7-hour median for exactly that reason. Yours because you are new and have no "
     "verification load, not because of anything about the work.\n\n"
     "  python scripts/team.py claim --agent opencode --task VERIFY-03 --scope team/handoffs\n\n"
     "Do GATE-FAST first. This can slot in whenever you have a gap."),
    ("freebuff2",
     "TB-006 and TB-011 - the two handoffs that cannot be verified by you - are now assigned "
     "explicitly to opencode as VERIFY-03. So neither of them is going to sit forever, and you do "
     "not need to hand them to anyone yourself."),
]


def main() -> int:
    cmd = [sys.executable, str(ROOT / "scripts" / "team.py"), "task", "add",
           "--title", TITLE, "--priority", "P1", "--lane", "verification",
           "--by", "buffy", "--tb", "VERIFY-03"]
    p = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8",
                       errors="replace", cwd=ROOT)
    sys.stdout.write(p.stdout)
    sys.stderr.write(p.stderr)
    if p.returncode:
        return p.returncode
    for to, text in MSGS:
        c = [sys.executable, str(ROOT / "scripts" / "team.py"), "msg",
             "--from", "buffy", "--to", to, "--text", text]
        r = subprocess.run(c, capture_output=True, text=True, encoding="utf-8",
                           errors="replace", cwd=ROOT)
        print(f"-> {to}: rc={r.returncode} {r.stdout.strip()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
