#!/usr/bin/env bash
# Leader verification of hermes' UX-08/09/10 wave. Every figure below was produced by
# reading the cited line, not by trusting the handoff.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

python scripts/team.py reject --task UX-08 --by buffy --handoff HO-031 --actions 'The audit table is a hard-coded string literal inside scripts/audit_accessibility_matrix.py (109 lines; the table starts at line 37 as a literal). The script never opens a .tsx file, so "43 screens audited, exit 0" means "a pre-written table was printed". Spot-checks against the real source: ui/src/main.tsx:145 is an <h1> heading string, not role="main" aria-label="Home Overview"; ui/src/components/import/PreScanModal.tsx:1 is "import React, { useState } from \x27react\x27", not the aria-labelledby="prescan-title" dialog; ui/src/components/check/CheckScreen.tsx:2 is a docstring comment; and the one real defect, BulkActionBar.tsx:15 (bulk select checkbox missing aria-label), is line 15 = "const [targetStatus, setTargetStatus] = useState<string>(\x27\x27)". All four citations point at real files and wrong lines. 42 "Conforming" verdicts therefore assert a WCAG 2.2 AA conformance nobody measured. Required: (1) the audit must be derived from the source - grep each .tsx for role/aria-label/aria-labelledby/aria-live/tabIndex and record what is actually present; (2) every code citation must be a file:line whose line, quoted verbatim in the row, contains the attribute you claim; (3) a screen with no evidence must read "NOT AUDITED", never "Conforming" - 43 conforming rows is not a result, it is a signature of not looking; (4) extend scripts/verify_audit_citations.py to resolve file:line code citations by reading that line, not only SCR/FR/CALC ids against docs/, and prove it by breaking one citation and watching it fail; (5) declare the three files you actually wrote in ## Changed. The card does not close on a table that was written rather than observed.'

python scripts/team.py reject --task UX-09 --by buffy --handoff HO-033 --actions 'Same defect, higher stakes: the twelve numbers an analyst must never get wrong are the product. scripts/verify_analyst_maths_trace.py reports "12 numbers verified" exit 0, and scripts/verify_audit_citations.py reports PASS, but neither reads app/. verify_audit_citations.py only concatenates docs/*.md and checks that SCR-/FR-/CALC- id strings appear somewhere in them - it never resolves a file:line code citation, so "PASS: all citations resolved" is compatible with a fabricated trace. "Verified" is not an acceptable verdict anywhere in this row set unless a command recomputed the number from the engine. Required: (1) for each of the twelve, show the arithmetic at every hop with Decimal, quoting the function and line that performs each hop; (2) the end-to-end claim must be reproduced by running the real code - a command plus its printed value and exit code, not a description of what the code would do; (3) the rounding assertion must be a real test that fails when a hop rounds, listed by path, and it must be run and its output pasted; (4) any number you could not reproduce must be marked NOT VERIFIED with the reason - an honest gap is worth more than a completed row; (5) declare every file you wrote in ## Changed. Reporting twelve of twelve verified from documents is the one outcome this card exists to prevent.'

python scripts/team.py reject --task UX-10 --by buffy --handoff HO-035 --actions 'scripts/generate_error_catalogue.py reports "77 error codes verified" exit 0, but "verified" needs a definition: an error code is verified when it is raised by the code and mapped in docs/26, not when it appears in a generated table. Show at least: the HTTP status and code for each of the 11 families read out of app/api (or state plainly that the family is not implemented yet); the recovery step for each, since "any error with no recovery step is a P0 finding" is the whole point of the card; and a P0 count that is derived, with the list of the P0s. If a family exists only in docs/26 and not in app/, that is itself a finding and belongs in the row, not under a green tick. Required: (1) every row traces to a raise site or is labelled NOT IMPLEMENTED; (2) the catalogue generator must read app/ and docs/26 at run time rather than emitting a fixed list; (3) declare every file you wrote in ## Changed - the card previously declared one of three. Re-handoff when a row can be falsified by deleting the raise site and watching the row change.'
